#!/usr/bin/env bash

####################################################################################
# Bashlight 	: 0.1.8
# Copyright		: 2018, MIT
# Author		: André Lademann <vergissberlin@googlemail.com>
# Repository	: https://github.com/vergissberlin/bashlight
####################################################################################


# Your settings here
if [ -z "${PATH_BASHLIGHT}" ]; then
	PATH_BASHLIGHT="${HOME}/bashlight"
fi

# Check update
# shellcheck source=update.bash
. "${PATH_BASHLIGHT}/update.bash" "${PATH_BASHLIGHT}"

####################################################################################
# Include modules
####################################################################################

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/src/aliases, instead of adding them here directly.

# shellcheck source=src/aliases.bash
[ -f "${PATH_BASHLIGHT}/src/aliases.bash"  ] && {
	# shellcheck source=src/aliases.bash
	. "${PATH_BASHLIGHT}/src/aliases.bash";
	setAliases
	}

# shellcheck source=src/logout.bash
[ -f "${PATH_BASHLIGHT}/src/logout.bash"   ] && {
	# shellcheck source=src/logout.bash
	. "${PATH_BASHLIGHT}/src/logout.bash";
	}

# shellcheck source=src/notify.bash
[ -f "${PATH_BASHLIGHT}/src/notify.bash"   ] && {
	# shellcheck source=src/notify.bash
	. "${PATH_BASHLIGHT}/src/notify.bash";
	}

# shellcheck source=src/settings.bash
[ -f "${PATH_BASHLIGHT}/src/settings.bash" ] && {
	# shellcheck source=src/settings.bash
	. "${PATH_BASHLIGHT}/src/settings.bash";
	}
# shellcheck source=src/prompt.bash
[ -f "${PATH_BASHLIGHT}/src/prompt.bash"   ] && {
	# shellcheck source=src/prompt.bash
	. "${PATH_BASHLIGHT}/src/prompt.bash";
	}
