Vagrant.configure("2") do |config|
  config.vm.box = "Microsoft/EdgeOnWindows10"
  config.vm.box_version = "1.0"

  # Always use Vagrant's default insecure key
  config.ssh.forward_agent    = true
  config.ssh.insert_key       = false
end
