Vagrant.configure("2") do |config|
  config.vm.box = "jacqinthebox/windowsserver2016"
  
  # Always use Vagrant's default insecure key
  config.ssh.forward_agent    = true
  config.ssh.insert_key       = false
end
