# -*- mode: ruby -*-
# vi: set ft=ruby :

####################################################################################
# Bashlight 	: 0.1.8
# Copyright		: 2018, MIT
# Author		: André Lademann <vergissberlin@googlemail.com>
# Repository	: https://github.com/vergissberlin/bashlight
####################################################################################

Vagrant.configure("2") do |config|

  config.vm.hostname = "bashlight-testbox-debian"
  config.vm.box = "debian/jessie64"
  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
    vb.memory = "1024"
  end

  config.vm.provision "file", source: "../fixtues/.bashrc", destination: ".bashrc"
  config.vm.provision "file", source: "../fixtues/.bash_aliases", destination: ".bash_aliases"
  config.vm.provision "shell", path: "before.sh"

  config.ssh.forward_agent    = true
  config.ssh.insert_key       = false

end
